vmalert:
  enabled: true
  spec:
    replicaCount: 2
    evaluationInterval: 1m
    podDisruptionBudget:
      minAvailable: 1
  ingress:
    enabled: true
    hosts:
      - vm-alert.${ingress_domain}
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "VictoriaMetrics Alert"
      gethomepage.dev/icon: sh-victoriametrics
      gethomepage.dev/group: "Admin"
      gethomepage.dev/external: "true"
  additionalNotifierConfigs:
    dns_sd_configs:
      - names:
          - vmalertmanager-vm-victoria-metrics-k8s-stack.vm.svc.cluster.local
        type: A
        port: 9093
    alert_relabel_configs:
      - action: replace
        source_labels: ["instance"]
        regex: '^192\.168\.253\.12[012]:.*$'
        target_label: node
        replacement: yig32
      - action: replace
        source_labels: ["instance"]
        regex: '^192\.168\.255\.23[012]:.*$'
        target_label: node
        replacement: yig16
      - action: replace
        source_labels: ["instance"]
        regex: '^192\.168\.253\.11[012]:.*$'
        target_label: node
        replacement: yig16
      - action: replace
        source_labels: ["instance"]
        regex: '^192\.168\.243\.10[01]:.*$'
        target_label: node
        replacement: dagon
      - action: replace
        source_labels: ["instance"]
        regex: '^192\.168\.253\.13[01]:.*$'
        target_label: node
        replacement: dagon
    # BEGIN generated by tools/relabel_alerts_groups.sh at 2025-08-24T03:39:10Z
      - target_label: alertgroup
        replacement: alertmanager.rules
        action: replace
        source_labels: ["alertname"]
        regex: '^(AlertmanagerFailedReload|AlertmanagerMembersInconsistent|AlertmanagerFailedToSendAlerts|AlertmanagerClusterFailedToSendAlerts|AlertmanagerClusterFailedToSendAlerts|AlertmanagerConfigInconsistent|AlertmanagerClusterDown|AlertmanagerClusterCrashlooping)$'
      - target_label: alertgroup
        replacement: config-reloaders
        action: replace
        source_labels: ["alertname"]
        regex: '^(ConfigReloaderSidecarErrors)$'
      - target_label: alertgroup
        replacement: etcd
        action: replace
        source_labels: ["alertname"]
        regex: '^(etcdMembersDown|etcdInsufficientMembers|etcdNoLeader|etcdHighNumberOfLeaderChanges|etcdHighNumberOfFailedGRPCRequests|etcdHighNumberOfFailedGRPCRequests|etcdGRPCRequestsSlow|etcdMemberCommunicationSlow|etcdHighNumberOfFailedProposals|etcdHighFsyncDurations|etcdHighFsyncDurations|etcdHighCommitDurations|etcdDatabaseQuotaLowSpace|etcdExcessiveDatabaseGrowth|etcdDatabaseHighFragmentationRatio)$'
      - target_label: alertgroup
        replacement: general.rules
        action: replace
        source_labels: ["alertname"]
        regex: '^(TargetDown|Watchdog|InfoInhibitor)$'
      - target_label: alertgroup
        replacement: kube-apiserver-slos
        action: replace
        source_labels: ["alertname"]
        regex: '^(KubeAPIErrorBudgetBurn|KubeAPIErrorBudgetBurn|KubeAPIErrorBudgetBurn|KubeAPIErrorBudgetBurn)$'
      - target_label: alertgroup
        replacement: kube-state-metrics
        action: replace
        source_labels: ["alertname"]
        regex: '^(KubeStateMetricsListErrors|KubeStateMetricsWatchErrors|KubeStateMetricsShardingMismatch|KubeStateMetricsShardsMissing)$'
      - target_label: alertgroup
        replacement: kubernetes-apps
        action: replace
        source_labels: ["alertname"]
        regex: '^(KubePodCrashLooping|KubePodNotReady|KubeDeploymentGenerationMismatch|KubeDeploymentReplicasMismatch|KubeDeploymentRolloutStuck|KubeStatefulSetReplicasMismatch|KubeStatefulSetGenerationMismatch|KubeStatefulSetUpdateNotRolledOut|KubeDaemonSetRolloutStuck|KubeContainerWaiting|KubeDaemonSetNotScheduled|KubeDaemonSetMisScheduled|KubeJobNotCompleted|KubeJobFailed|KubeHpaReplicasMismatch|KubeHpaMaxedOut|KubePdbNotEnoughHealthyPods)$'
      - target_label: alertgroup
        replacement: kubernetes-resources
        action: replace
        source_labels: ["alertname"]
        regex: '^(KubeCPUOvercommit|KubeMemoryOvercommit|KubeCPUQuotaOvercommit|KubeMemoryQuotaOvercommit|KubeQuotaAlmostFull|KubeQuotaFullyUsed|KubeQuotaExceeded|CPUThrottlingHigh)$'
      - target_label: alertgroup
        replacement: kubernetes-storage
        action: replace
        source_labels: ["alertname"]
        regex: '^(KubePersistentVolumeFillingUp|KubePersistentVolumeFillingUp|KubePersistentVolumeInodesFillingUp|KubePersistentVolumeInodesFillingUp|KubePersistentVolumeErrors)$'
      - target_label: alertgroup
        replacement: kubernetes-system
        action: replace
        source_labels: ["alertname"]
        regex: '^(KubeVersionMismatch|KubeClientErrors)$'
      - target_label: alertgroup
        replacement: kubernetes-system-apiserver
        action: replace
        source_labels: ["alertname"]
        regex: '^(KubeClientCertificateExpiration|KubeClientCertificateExpiration|KubeAggregatedAPIErrors|KubeAggregatedAPIDown|KubeAPIDown|KubeAPITerminatedRequests)$'
      - target_label: alertgroup
        replacement: kubernetes-system-controller-manager
        action: replace
        source_labels: ["alertname"]
        regex: '^(KubeControllerManagerDown)$'
      - target_label: alertgroup
        replacement: kubernetes-system-kube-proxy
        action: replace
        source_labels: ["alertname"]
        regex: '^(KubeProxyDown)$'
      - target_label: alertgroup
        replacement: kubernetes-system-kubelet
        action: replace
        source_labels: ["alertname"]
        regex: '^(KubeNodeNotReady|KubeNodePressure|KubeNodeUnreachable|KubeletTooManyPods|KubeNodeReadinessFlapping|KubeNodeEviction|KubeletPlegDurationHigh|KubeletPodStartUpLatencyHigh|KubeletClientCertificateExpiration|KubeletClientCertificateExpiration|KubeletServerCertificateExpiration|KubeletServerCertificateExpiration|KubeletClientCertificateRenewalErrors|KubeletServerCertificateRenewalErrors|KubeletDown)$'
      - target_label: alertgroup
        replacement: kubernetes-system-scheduler
        action: replace
        source_labels: ["alertname"]
        regex: '^(KubeSchedulerDown)$'
      - target_label: alertgroup
        replacement: node-exporter
        action: replace
        source_labels: ["alertname"]
        regex: '^(NodeFilesystemSpaceFillingUp|NodeFilesystemSpaceFillingUp|NodeFilesystemAlmostOutOfSpace|NodeFilesystemAlmostOutOfSpace|NodeFilesystemFilesFillingUp|NodeFilesystemFilesFillingUp|NodeFilesystemAlmostOutOfFiles|NodeFilesystemAlmostOutOfFiles|NodeNetworkReceiveErrs|NodeNetworkTransmitErrs|NodeHighNumberConntrackEntriesUsed|NodeTextFileCollectorScrapeError|NodeClockSkewDetected|NodeClockNotSynchronising|NodeRAIDDegraded|NodeRAIDDiskFailure|NodeFileDescriptorLimit|NodeFileDescriptorLimit|NodeCPUHighUsage|NodeSystemSaturation|NodeMemoryMajorPagesFaults|NodeMemoryHighUtilization|NodeDiskIOSaturation|NodeSystemdServiceFailed|NodeSystemdServiceCrashlooping|NodeBondingDegraded)$'
      - target_label: alertgroup
        replacement: node-network
        action: replace
        source_labels: ["alertname"]
        regex: '^(NodeNetworkInterfaceFlapping)$'
      - target_label: alertgroup
        replacement: prometheus
        action: replace
        source_labels: ["alertname"]
        regex: '^(PrometheusBadConfig|PrometheusSDRefreshFailure|PrometheusKubernetesListWatchFailures|PrometheusNotificationQueueRunningFull|PrometheusErrorSendingAlertsToSomeAlertmanagers|PrometheusNotConnectedToAlertmanagers|PrometheusTSDBReloadsFailing|PrometheusTSDBCompactionsFailing|PrometheusNotIngestingSamples|PrometheusDuplicateTimestamps|PrometheusOutOfOrderTimestamps|PrometheusRemoteStorageFailures|PrometheusRemoteWriteBehind|PrometheusRemoteWriteDesiredShards|PrometheusRuleFailures|PrometheusMissingRuleEvaluations|PrometheusTargetLimitHit|PrometheusLabelLimitHit|PrometheusScrapeBodySizeLimitHit|PrometheusScrapeSampleLimitHit|PrometheusTargetSyncFailure|PrometheusHighQueryLoad|PrometheusErrorSendingAlertsToAnyAlertmanager)$'
      - target_label: alertgroup
        replacement: prometheus-operator
        action: replace
        source_labels: ["alertname"]
        regex: '^(PrometheusOperatorListErrors|PrometheusOperatorWatchErrors|PrometheusOperatorSyncFailed|PrometheusOperatorReconcileErrors|PrometheusOperatorStatusUpdateErrors|PrometheusOperatorNodeLookupErrors|PrometheusOperatorNotReady|PrometheusOperatorRejectedResources)$'
    # END generated by tools/relabel_alerts_groups.sh

defaultRules:
  groups:
    vmcluster:
      spec:
        interval: 1m
    vmagent:
      spec:
        interval: 1m
    vmalert:
      spec:
        interval: 1m