# curl -s https://prometheus/api/v1/rules?type=alert | jq . > prom_rules.json
echo "    additionalAlertRelabelConfigs:"
echo "    # BEGIN generated by tools/relabel_alerts_groups.sh at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
for g in `cat prom_rules.json| jq -r '.data.groups[] .name' | xargs`; do
  echo "      - target_label: alertgroup"
  echo "        replacement: ${g}"
  echo "        action: replace"
  echo "        source_labels: [\"alertname\"]"
  echo "        regex: '^(`cat prom_rules.json | jq -r --arg g "$g" '.data.groups[] | select(.name == $g) | .rules[] .name' | xargs | sed 's/ /\|/g'`)\$'"
done
echo "    # END generated by tools/relabel_alerts_groups.sh"